#!/bin/sh
# Write .env with the secrets the Compose stack needs.
#
# Compose reads .env from this directory automatically. The file is gitignored;
# it holds real credentials, even on a laptop.
set -eu

cd "$(dirname "$0")"

if [ -f .env ]; then
    echo ".env already exists; delete it first to generate new secrets." >&2
    exit 1
fi

# openssl ships with macOS and every mainstream Linux; fall back to the kernel's
# entropy pool so this also works in a minimal container.
random_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

cat > .env <<EOF
# Generated by generate-env.sh. Regenerating the JWT secret signs everyone out.
BUILDMAX_JWT_SECRET=$(random_hex)
BUILDMAX_DATABASE_PASSWORD=$(random_hex)

# Optional. Without it the Portal runs but conversations cannot reach a model.
# Any OpenAI-compatible provider; the endpoint is set in server.yaml.
BUILDMAX_CONVERSATION_MODEL_API_KEY=

# Host ports. Changing BUILDMAX_PORTAL_PORT also means changing cors_origin in
# server.yaml, which has to name the origin the Portal is served from.
BUILDMAX_SERVER_PORT=5678
BUILDMAX_PORTAL_PORT=8080
EOF

chmod 600 .env
echo "Wrote $(pwd)/.env"
echo
echo "Next:"
echo "  docker compose up -d"
echo "  docker compose exec server buildmax-server user create you@example.com"
echo "  docker compose exec server buildmax-server user login-code you@example.com"
