version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/gui"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/portal"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/desktop/frontend"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns: ["*"]
        update-types: [minor, patch]
