import type { ApiArtifact } from "../../lib/api/types"

/** The name to lead with: the title if the producer gave one, else the file. */
export function artifactLabel(artifact: ApiArtifact): string {
  return artifact.title?.trim() || artifact.filename
}

export function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  const units = ["KB", "MB", "GB"]
  let value = bytes / 1024
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit += 1
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`
}

export function formatTime(rfc3339: string): string {
  return new Date(rfc3339).toLocaleString()
}

/** What produced the file, in the words a reader uses rather than the stored enum. */
export function sourceLabel(artifact: ApiArtifact): string {
  switch (artifact.source_type) {
    case "task_run":
      return "Produced by a run"
    case "agent":
      return "Saved by an agent"
    case "system":
      return "Generated by BuildMax"
    default:
      return "Uploaded"
  }
}

/**
 * mayDelete mirrors the server: an admin or owner may remove anything the team
 * holds, and anyone else only what they uploaded themselves. It is duplicated
 * here to decide whether to offer the button, never to decide the outcome.
 */
export function mayDelete(
  artifact: ApiArtifact,
  userId?: string,
  role?: string | null
): boolean {
  if (role === "admin" || role === "owner") return true
  return artifact.created_by_type === "user" && !!userId && artifact.created_by_id === userId
}
