import { useCallback, useEffect, useRef, useState } from "react"
import type { ApiArtifact } from "../../lib/api/types"
import { getErrorMessage } from "../../lib/errorMessage"
import { downloadAuthenticated } from "../../lib/download"
import { artifactContentUrl, deleteArtifact, listArtifacts, uploadArtifact } from "./api"
import { ArtifactPreview } from "./ArtifactPreview"

const PAGE_SIZE = 50

interface SpaceArtifactsSectionProps {
  teamId: string | null
  token: string | null
  currentUserId?: string
  currentUserIsOwner: boolean
  currentUserRole?: string | null
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  const units = ["KB", "MB", "GB"]
  let value = bytes / 1024
  let unit = 0
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024
    unit += 1
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[unit]}`
}

function formatTime(rfc3339: string): string {
  return new Date(rfc3339).toLocaleString()
}

/** What produced the file, in the words a reader uses rather than the stored enum. */
function sourceLabel(artifact: ApiArtifact): string {
  switch (artifact.source_type) {
    case "task_run":
      return "Produced by a run"
    case "agent":
      return "Saved by an agent"
    case "system":
      return "Generated by BuildMax"
    default:
      return "Uploaded"
  }
}

/**
 * mayDelete mirrors the server: an admin or owner may remove anything the team
 * holds, and anyone else only what they uploaded themselves. It is duplicated
 * here to decide whether to offer the button, never to decide the outcome.
 */
function mayDelete(artifact: ApiArtifact, userId?: string, role?: string | null): boolean {
  if (role === "admin" || role === "owner") return true
  return artifact.created_by_type === "user" && !!userId && artifact.created_by_id === userId
}

export function SpaceArtifactsSection({
  teamId,
  token,
  currentUserId,
  currentUserIsOwner,
  currentUserRole,
}: SpaceArtifactsSectionProps) {
  const [items, setItems] = useState<ApiArtifact[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [busyId, setBusyId] = useState<string | null>(null)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [preview, setPreview] = useState<ApiArtifact | null>(null)
  const fileInput = useRef<HTMLInputElement>(null)

  const role = currentUserRole ?? (currentUserIsOwner ? "owner" : null)

  const load = useCallback(
    (offset: number) => {
      if (!teamId || !token) return
      setLoading(true)
      setError(null)
      listArtifacts(teamId, token, { limit: PAGE_SIZE, offset })
        .then((res) => {
          setItems((prev) => (offset === 0 ? res.items : [...prev, ...res.items]))
          setTotal(res.total)
        })
        .catch((err) => setError(getErrorMessage(err, "Failed to load artifacts")))
        .finally(() => setLoading(false))
    },
    [teamId, token]
  )

  useEffect(() => {
    load(0)
  }, [load])

  function pickFile() {
    fileInput.current?.click()
  }

  async function onFileChosen(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    // Cleared straight away so choosing the same file twice still fires.
    event.target.value = ""
    if (!file || !teamId || !token) return
    setUploading(true)
    setError(null)
    try {
      await uploadArtifact(teamId, token, file)
      load(0)
    } catch (err) {
      setError(getErrorMessage(err, "Upload failed"))
    } finally {
      setUploading(false)
    }
  }

  async function onDownload(artifact: ApiArtifact) {
    if (!token) return
    setBusyId(artifact.id)
    setError(null)
    try {
      await downloadAuthenticated(artifactContentUrl(artifact.id), token, artifact.filename)
    } catch (err) {
      setError(getErrorMessage(err, "Download failed"))
    } finally {
      setBusyId(null)
    }
  }

  async function onDelete(artifact: ApiArtifact) {
    if (!token) return
    setBusyId(artifact.id)
    setError(null)
    try {
      await deleteArtifact(artifact.id, token)
      setItems((prev) => prev.filter((a) => a.id !== artifact.id))
      setTotal((prev) => Math.max(0, prev - 1))
    } catch (err) {
      setError(getErrorMessage(err, "Delete failed"))
    } finally {
      setBusyId(null)
    }
  }

  return (
    <section className="settings-section">
      <h2 className="settings-section__title">Artifacts</h2>
      <p className="settings-section__hint">
        Files this space keeps. Each one has a stable reference that any member can open, and its
        content never changes — a new version is a new artifact.
      </p>

      <div className="audit-export">
        <button
          type="button"
          className="page-activity__action-btn"
          onClick={pickFile}
          disabled={uploading || !teamId}
        >
          {uploading ? "Uploading…" : "Upload a file"}
        </button>
        <input
          ref={fileInput}
          type="file"
          className="artifact-list__file-input"
          onChange={onFileChosen}
          hidden
        />
      </div>

      {error ? (
        <p className="settings-section__error" role="alert">
          {error}
        </p>
      ) : null}

      {!error && items.length === 0 && !loading ? (
        <p className="page-activity__empty">Nothing kept here yet.</p>
      ) : null}

      {items.length > 0 ? (
        <ul className="artifact-list">
          {items.map((artifact) => (
            <li key={artifact.id} className="artifact-row">
              <div className="artifact-row__main">
                <span className="artifact-row__name">{artifact.title || artifact.filename}</span>
                <span className="artifact-row__meta">
                  {artifact.filename} · {formatSize(artifact.size_bytes)} · {sourceLabel(artifact)}
                </span>
              </div>
              <div className="artifact-row__meta">
                <code className="artifact-row__id">{artifact.id}</code>
                <time>{formatTime(artifact.created_at)}</time>
              </div>
              <div className="artifact-row__actions">
                {/* Only what the server said it will serve for display. A type
                    it refuses to render inline is not one to open in a viewer. */}
                {artifact.inline ? (
                  <button
                    type="button"
                    className="page-activity__action-btn"
                    onClick={() => setPreview(artifact)}
                  >
                    Preview
                  </button>
                ) : null}
                <button
                  type="button"
                  className="page-activity__action-btn"
                  onClick={() => onDownload(artifact)}
                  disabled={busyId === artifact.id}
                >
                  Download
                </button>
                {mayDelete(artifact, currentUserId, role) ? (
                  <button
                    type="button"
                    className="page-activity__action-btn"
                    onClick={() => onDelete(artifact)}
                    disabled={busyId === artifact.id}
                  >
                    Delete
                  </button>
                ) : null}
              </div>
            </li>
          ))}
        </ul>
      ) : null}

      {loading ? <p className="page-activity__empty">Loading…</p> : null}

      {items.length < total ? (
        <button
          type="button"
          className="page-activity__action-btn"
          onClick={() => load(items.length)}
          disabled={loading}
        >
          Show older ({total - items.length} more)
        </button>
      ) : null}

      <ArtifactPreview artifact={preview} token={token} onClose={() => setPreview(null)} />
    </section>
  )
}
