import type { ExploreNode } from "../lib/types"

/**
 * Demo workspace directory structure for Explore page.
 * Root is a folder; files have content for the viewer.
 */
export const MOCK_EXPLORE_TREE: ExploreNode = {
  id: "root",
  name: "Workspace",
  type: "folder",
  children: [
    {
      id: "root/projects",
      name: "projects",
      type: "folder",
      children: [
        {
          id: "root/projects/sales",
          name: "sales",
          type: "folder",
          children: [
            {
              id: "root/projects/sales/report.md",
              name: "report.md",
              type: "file",
              content: `# Sales Report — February 2026

## Summary
- Revenue: $135,000 (+12% MoM)
- Top region: West Coast ($52,000)
- Top product: Enterprise Plan ($48,000)

## Notes
Generated by BuildMax agent.`,
            },
            {
              id: "root/projects/sales/data.csv",
              name: "data.csv",
              type: "file",
              content: `date,region,revenue
2026-02-01,West Coast,52000
2026-02-01,East Coast,41000
2026-02-01,Central,42000`,
            },
          ],
        },
        {
          id: "root/projects/engineering",
          name: "engineering",
          type: "folder",
          children: [
            {
              id: "root/projects/engineering/README.md",
              name: "README.md",
              type: "file",
              content: `# Engineering

API Gateway refactor and test coverage dashboard.

## Commands
- \`make test\` — run tests
- \`make build\` — build binary`,
            },
          ],
        },
      ],
    },
    {
      id: "root/docs",
      name: "docs",
      type: "folder",
      children: [
        {
          id: "root/docs/readme.md",
          name: "readme.md",
          type: "file",
          content: `# Workspace Docs

Welcome to the workspace. Use Explore to browse folders and open files.`,
        },
        {
          id: "root/docs/design.md",
          name: "design.md",
          type: "file",
          content: `# Design Notes

- Intent over tools
- Text as primary representation
- State versioned and reversible`,
        },
      ],
    },
    {
      id: "root/notes.txt",
      name: "notes.txt",
      type: "file",
      content: "Quick notes\n\n- Item one\n- Item two\n- Item three",
    },
  ],
}

function findNodeById(node: ExploreNode, id: string): ExploreNode | undefined {
  if (node.id === id) return node
  if (node.type === "folder") {
    for (const child of node.children) {
      const found = findNodeById(child, id)
      if (found) return found
    }
  }
  return undefined
}

/** Get direct children of a folder node, or empty array if not found / not a folder. */
export function getExploreChildren(
  root: ExploreNode,
  folderId: string,
): ExploreNode[] {
  if (folderId === "" || folderId === "root") {
    return root.type === "folder" ? root.children : []
  }
  const node = findNodeById(root, folderId)
  return node?.type === "folder" ? node.children : []
}

/** Get a node by id. */
export function getExploreNodeById(
  root: ExploreNode,
  id: string,
): ExploreNode | undefined {
  if (id === "" || id === "root") return root
  return findNodeById(root, id)
}
