import type { Workspace, Project, Task, Artifact } from "./types"

// --- Mock workspaces (UUID ids) ---

const MOCK_WORKSPACES: Workspace[] = [
  { id: "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d", name: "Sales Team" },
  { id: "b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e", name: "Engineering" },
  { id: "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f", name: "Marketing" },
]

// --- Mock projects (at least 2 per workspace; ids unique globally) ---

export const MOCK_PROJECTS: Project[] = [
  // Sales Team
  {
    id: "p1",
    workspaceId: MOCK_WORKSPACES[0].id,
    name: "Monthly Sales Report",
    status: "active",
    updatedAtLabel: "Updated 2h ago",
  },
  {
    id: "p2",
    workspaceId: MOCK_WORKSPACES[0].id,
    name: "Pricing Strategy Draft",
    status: "active",
    updatedAtLabel: "Updated 1d ago",
  },
  {
    id: "p3",
    workspaceId: MOCK_WORKSPACES[0].id,
    name: "Customer QBR Pack",
    status: "paused",
    updatedAtLabel: "Updated 1w ago",
  },
  // Engineering
  {
    id: "p4",
    workspaceId: MOCK_WORKSPACES[1].id,
    name: "API Gateway Refactor",
    status: "active",
    updatedAtLabel: "Updated 3h ago",
  },
  {
    id: "p5",
    workspaceId: MOCK_WORKSPACES[1].id,
    name: "Test Coverage Dashboard",
    status: "active",
    updatedAtLabel: "Updated yesterday",
  },
  // Marketing
  {
    id: "p6",
    workspaceId: MOCK_WORKSPACES[2].id,
    name: "Q2 Campaign Plan",
    status: "active",
    updatedAtLabel: "Updated 5h ago",
  },
  {
    id: "p7",
    workspaceId: MOCK_WORKSPACES[2].id,
    name: "Social Content Calendar",
    status: "paused",
    updatedAtLabel: "Updated 2d ago",
  },
]

// --- Mock tasks ---

export const MOCK_TASKS: Task[] = [
  { id: "t1", projectId: "p1", title: "Generated sales report", status: "success", timeLabel: "Today 10:42 AM", summary: "Created a monthly sales report with revenue and growth charts." },
  { id: "t2", projectId: "p1", title: "Imported February data", status: "success", timeLabel: "Today 10:40 AM", summary: "Added the new February dataset for analysis." },
  { id: "t3", projectId: "p2", title: "Drafted initial pricing model", status: "success", timeLabel: "Yesterday 3:15 PM", summary: "Created a pricing comparison table with competitor benchmarks." },
  { id: "t4", projectId: "p3", title: "Compiled Q4 review slides", status: "failed", timeLabel: "Feb 10, 1:20 PM", summary: "Attempted to compile slides but missing data source." },
  { id: "t5", projectId: "p4", title: "Migrated auth middleware", status: "success", timeLabel: "Today 9:00 AM", summary: "Moved auth checks into shared middleware." },
  { id: "t6", projectId: "p4", title: "Added rate limiting", status: "success", timeLabel: "Yesterday 4:30 PM", summary: "Implemented per-IP rate limits on gateway." },
  { id: "t7", projectId: "p5", title: "Generated coverage report", status: "success", timeLabel: "Feb 12, 2:00 PM", summary: "Coverage now at 78% for core packages." },
  { id: "t8", projectId: "p6", title: "Drafted campaign brief", status: "success", timeLabel: "Today 11:00 AM", summary: "Created Q2 campaign objectives and channels." },
  { id: "t9", projectId: "p7", title: "Scheduled March posts", status: "success", timeLabel: "Feb 14, 10:00 AM", summary: "Added 12 posts to the content calendar." },
]

// --- Mock artifacts ---

export const MOCK_ARTIFACTS: Artifact[] = [
  { id: "a1", projectId: "p1", title: "Sales Analysis — February", kind: "report", preview: "## Sales Analysis — February\n\n**Revenue:** $135,000\n**Growth:** +12% month-over-month\n\nTop region: West Coast ($52,000)\nTop product: Enterprise Plan ($48,000)\n\n---\n\n*Generated by BuildMax agent.*" },
  { id: "a2", projectId: "p1", title: "Revenue Trend Chart", kind: "chart", preview: "[Chart placeholder]\n\nJan: $120,000\nFeb: $135,000\n\nTrend: +12% MoM" },
  { id: "a3", projectId: "p1", title: "cleaned_data.csv", kind: "data", preview: "date,region,revenue\n2026-02-01,West Coast,52000\n2026-02-01,East Coast,41000\n2026-02-01,Central,42000" },
  { id: "a4", projectId: "p2", title: "Pricing Comparison Table", kind: "report", preview: "## Pricing Comparison\n\n| Plan | Us | Competitor A | Competitor B |\n|------|-----|-------------|-------------|\n| Starter | $19 | $25 | $22 |\n| Pro | $49 | $59 | $55 |\n| Enterprise | $149 | $199 | $179 |" },
  { id: "a5", projectId: "p4", title: "Gateway API Spec", kind: "report", preview: "## Gateway API\n\n- POST /auth\n- GET /api/v1/resources\n- Rate limit: 100/min per IP" },
  { id: "a6", projectId: "p5", title: "Coverage Summary", kind: "report", preview: "## Coverage\n\n- internal/agent: 82%\n- internal/llm: 75%\n- internal/tools: 78%" },
  { id: "a7", projectId: "p6", title: "Q2 Campaign Brief", kind: "report", preview: "## Q2 Campaign\n\nObjectives: awareness, sign-ups.\nChannels: paid social, email, blog." },
]

// --- Workspace helpers ---

export function listWorkspaces(): Workspace[] {
  return [...MOCK_WORKSPACES]
}

export function getWorkspaceById(id: string): Workspace | undefined {
  return MOCK_WORKSPACES.find((w) => w.id === id)
}

// --- Lookup helpers ---

export function getProjectById(projectId: string): Project | undefined {
  return MOCK_PROJECTS.find((p) => p.id === projectId)
}

export function listProjectsForWorkspace(workspaceId: string): Project[] {
  return MOCK_PROJECTS.filter((p) => p.workspaceId === workspaceId)
}

export function listTasksForWorkspace(workspaceId: string): Task[] {
  const projectIds = listProjectsForWorkspace(workspaceId).map((p) => p.id)
  return MOCK_TASKS.filter((t) => projectIds.includes(t.projectId))
}

export function listArtifactsForWorkspace(workspaceId: string): Artifact[] {
  const projectIds = listProjectsForWorkspace(workspaceId).map((p) => p.id)
  return MOCK_ARTIFACTS.filter((a) => projectIds.includes(a.projectId))
}

export function listTasksForProject(projectId: string): Task[] {
  return MOCK_TASKS.filter((t) => t.projectId === projectId)
}

export function listArtifactsForProject(projectId: string): Artifact[] {
  return MOCK_ARTIFACTS.filter((a) => a.projectId === projectId)
}

export function getTaskById(
  projectId: string,
  taskId: string,
): Task | undefined {
  return MOCK_TASKS.find((t) => t.projectId === projectId && t.id === taskId)
}

export function getArtifactById(
  projectId: string,
  artifactId: string,
): Artifact | undefined {
  return MOCK_ARTIFACTS.find(
    (a) => a.projectId === projectId && a.id === artifactId,
  )
}
