import type { Workspace, Project, Task, Artifact } from "./types"

// --- Mock workspace ---

export const MOCK_WORKSPACE: Workspace = {
  id: "ws1",
  name: "Sales Team",
}

// --- Mock projects ---

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    workspaceId: "ws1",
    name: "Monthly Sales Report",
    status: "active",
    updatedAtLabel: "Updated 2h ago",
  },
  {
    id: "p2",
    workspaceId: "ws1",
    name: "Pricing Strategy Draft",
    status: "active",
    updatedAtLabel: "Updated 1d ago",
  },
  {
    id: "p3",
    workspaceId: "ws1",
    name: "Customer QBR Pack",
    status: "paused",
    updatedAtLabel: "Updated 1w ago",
  },
]

// --- Mock tasks ---

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    title: "Generated sales report",
    status: "success",
    timeLabel: "Today 10:42 AM",
    summary: "Created a monthly sales report with revenue and growth charts.",
  },
  {
    id: "t2",
    projectId: "p1",
    title: "Imported February data",
    status: "success",
    timeLabel: "Today 10:40 AM",
    summary: "Added the new February dataset for analysis.",
  },
  {
    id: "t3",
    projectId: "p2",
    title: "Drafted initial pricing model",
    status: "success",
    timeLabel: "Yesterday 3:15 PM",
    summary: "Created a pricing comparison table with competitor benchmarks.",
  },
  {
    id: "t4",
    projectId: "p3",
    title: "Compiled Q4 review slides",
    status: "failed",
    timeLabel: "Feb 10, 1:20 PM",
    summary: "Attempted to compile slides but missing data source.",
  },
]

// --- Mock artifacts ---

export const MOCK_ARTIFACTS: Artifact[] = [
  {
    id: "a1",
    projectId: "p1",
    title: "Sales Analysis — February",
    kind: "report",
    preview:
      "## Sales Analysis — February\n\n**Revenue:** $135,000\n**Growth:** +12% month-over-month\n\nTop region: West Coast ($52,000)\nTop product: Enterprise Plan ($48,000)\n\n---\n\n*Generated by BuildMax agent.*",
  },
  {
    id: "a2",
    projectId: "p1",
    title: "Revenue Trend Chart",
    kind: "chart",
    preview:
      "[Chart placeholder]\n\nJan: $120,000\nFeb: $135,000\n\nTrend: +12% MoM",
  },
  {
    id: "a3",
    projectId: "p1",
    title: "cleaned_data.csv",
    kind: "data",
    preview:
      "date,region,revenue\n2026-02-01,West Coast,52000\n2026-02-01,East Coast,41000\n2026-02-01,Central,42000",
  },
  {
    id: "a4",
    projectId: "p2",
    title: "Pricing Comparison Table",
    kind: "report",
    preview:
      "## Pricing Comparison\n\n| Plan | Us | Competitor A | Competitor B |\n|------|-----|-------------|-------------|\n| Starter | $19 | $25 | $22 |\n| Pro | $49 | $59 | $55 |\n| Enterprise | $149 | $199 | $179 |",
  },
]

// --- Lookup helpers ---

export function getProjectById(projectId: string): Project | undefined {
  return MOCK_PROJECTS.find((p) => p.id === projectId)
}

export function listProjectsForWorkspace(workspaceId: string): Project[] {
  return MOCK_PROJECTS.filter((p) => p.workspaceId === workspaceId)
}

export function listTasksForProject(projectId: string): Task[] {
  return MOCK_TASKS.filter((t) => t.projectId === projectId)
}

export function listArtifactsForProject(projectId: string): Artifact[] {
  return MOCK_ARTIFACTS.filter((a) => a.projectId === projectId)
}

export function getTaskById(
  projectId: string,
  taskId: string,
): Task | undefined {
  return MOCK_TASKS.find((t) => t.projectId === projectId && t.id === taskId)
}

export function getArtifactById(
  projectId: string,
  artifactId: string,
): Artifact | undefined {
  return MOCK_ARTIFACTS.find(
    (a) => a.projectId === projectId && a.id === artifactId,
  )
}
